# Stage 1: Build Stage
FROM ubuntu:20.04 AS builder

# Install Java and Maven
RUN apt-get update && \
    apt-get install -y openjdk-11-jdk maven && \
    apt-get clean;

# Set working directory
WORKDIR /app

# Copy files to container
COPY pom.xml .
COPY src/ ./src/

# Build the application
RUN mvn clean package

# Stage 2: Run Stage
FROM gcr.io/distroless/java:11

# Set working directory
WORKDIR /app

# Copy built JAR file from build stage
COPY --from=builder /app/target/calculator-1.0-SNAPSHOT.jar /app/calculator.jar

# Run the application
CMD ["java", "-jar", "/app/calculator.jar"]

