FROM ubuntu AS ubun

WORKDIR /app

COPY . .

RUN apt-get updates && apt-get install -y openjdk-17-jdk
RUN javac calculator.java

ENTRYPOINT ["java"]

FROM gcr.io/distroless/java

COPY --from=ubun /app /app

CMD ["calculator"]
