#stage 1: creating a foundation image

FROM ubuntu AS ubun

WORKDIR /app

COPY dockerfile /app/
COPY requirements.txt /app/
COPY devops /app/

RUN apt-get update && apt-get install -y python3 python3-pip python3-venv

SHELL ["/bin/bash", "-c"]

RUN python3 -m venv venv1 && \
    source venv1/bin/activate && \
    pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

#stage 2: creating a distroless image for python

FROM gcr.io/distroless/python3

COPY --from=ubun /app /app

SHELL ["/bin/bash", "-c"]

CMD source venv1/bin/activate && python3 manage.py runserver 0.0.0.0:8000
